baseURL = "https://www.valoforce.com"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "Valoforce"
title = "Valoforce"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "Valoforce"
[params.banner]
heading = "Valoforce, your IT partner to make the best decisions"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Contact us for more information."
[params.cookies]
enable = false
expire_days = 2
[params.footer]
address = "Bordeaux, France"
content = "This may be a good place to introduce yourself and your site or include some credits."
copyright = "Copyright &copy; 2021 valoforce.com"
hours = "Monday–Friday: 9:00AM–5:00PM"
title = "About Valoforce"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "contact@valoforce.com"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "https://twitter.com/valoforce"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
